spring.application.name=MailServiceProject

server.port=8080

spring.mail.host=smtp.gmail.com

spring.mail.port=587

spring.mail.username=neerajpatel883981@gmail.com

spring.mail.password= pjhd yjtp wcme ibgz

spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.starttls.enable=true